name: Build

on:
  
  push:
    branches-ignore: [main]

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update

      - name: Install xalan
        run: sudo apt-get install -y xalan

      - name: Install fop
        run: sudo apt-get install -y fop

      - name: build
        run: ant init

      - name: build
        run: ant build

      - name: Archive results
        uses: actions/upload-artifact@v3.1.1
        with:
          name: FPV-Bibliography
          path: build

  test-build:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: buFPV-Bibliographyild
          
      - name: Display structure of downloaded files
        run: ls -R
